import os

# Credentials
USERNAME = os.environ.get("USERNAME")
PASSWORD = os.environ.get("PASSWORD")

# Entity codes from the Mobility database
GTFS_CATALOG_OF_SOURCES_CODE = os.environ.get("GTFS_CATALOG_OF_SOURCES_CODE")
GBFS_CATALOG_OF_SOURCES_CODE = os.environ.get("GBFS_CATALOG_OF_SOURCES_CODE")
GTFS_SCHEDULE_DATA_FORMAT = os.environ.get("GTFS_SCHEDULE_DATA_FORMAT")

# Properties from the Mobility database
INSTANCE_PROP = os.environ.get("INSTANCE_PROP")
SOURCE_ENTITY_PROP = os.environ.get("SOURCE_ENTITY_PROP")
MAIN_TIMEZONE_PROP = os.environ.get("MAIN_TIMEZONE_PROP")
MAIN_LANGUAGE_CODE_PROP = os.environ.get("MAIN_LANGUAGE_CODE_PROP")
START_SERVICE_DATE_PROP = os.environ.get("START_SERVICE_DATE_PROP")
END_SERVICE_DATE_PROP = os.environ.get("END_SERVICE_DATE_PROP")
START_TIMESTAMP_PROP = os.environ.get("START_TIMESTAMP_PROP")
END_TIMESTAMP_PROP = os.environ.get("END_TIMESTAMP_PROP")
MD5_HASH_PROP = os.environ.get("MD5_HASH_PROP")
DATASET_VERSION_PROP = os.environ.get("DATASET_VERSION_PROP")
STABLE_URL_PROP = os.environ.get("STABLE_URL_PROP")
ORDER_PROP = os.environ.get("ORDER_PROP")
BOUNDING_BOX_PROP = os.environ.get("BOUNDING_BOX_PROP")
BOUNDING_OCTAGON_PROP = os.environ.get("BOUNDING_OCTAGON_PROP")
NUM_OF_STOPS_PROP = os.environ.get("NUM_OF_STOPS_PROP")
NUM_OF_STATIONS_PROP = os.environ.get("NUM_OF_STATIONS_PROP")
NUM_OF_ENTRANCES_PROP = os.environ.get("NUM_OF_ENTRANCES_PROP")
NUM_OF_AGENCIES_PROP = os.environ.get("NUM_OF_AGENCIES_PROP")
NUM_OF_ROUTES_PROP = os.environ.get("NUM_OF_ROUTES_PROP")
ROUTE_TYPE_PROP = os.environ.get("ROUTE_TYPE_PROP")
CATALOG_PROP = os.environ.get("CATALOG_PROP")

# External services
SPARQL_URL = os.environ.get("SPARQL_URL")
SPARQL_BIGDATA_URL = os.environ.get("SPARQL_BIGDATA_URL")
API_URL = os.environ.get("API_URL")
